version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: webapp:ahernp
    environment:
      - AHERNP_DATABASE_USER
      - AHERNP_DATABASE_PASSWORD
      - AHERNP_DATABASE_NAME
      - POSTGRES_PASSWORD
      - DJANGO_SECRET_KEY
    command: uwsgi --socket /opt/ahernp/uwsgi.sock --module project.wsgi --chmod-socket=777
    volumes:
      - ./django:/opt/ahernp
    depends_on:
      - db
  # node:
  #   image: node
  #   volumes:
  #     - .:/opt/ahernp
  #   command: npm install
  nginx:
    image: nginx:stable
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/uwsgi_params:/opt/ahernp/uwsgi_params
      - ./django/static:/opt/ahernp/static
      - ./django/media:/opt/ahernp/media
      - ./django/uwsgi.sock:/opt/ahernp/uwsgi.sock
      - ./react/build:/opt/ahernp/build
    depends_on:
      - webapp
    ports:
      - "80:80"
